apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/amanirshad/aegis-gitops.git
    targetRevision: main
    path: clusters/local/observability

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true